### ISSUE TITLE
Compile error in 3.1.x series

### ISSUE THREAD

**Issue by martinisoft** [boundary/boundary-meter_cookbook#7]
On Chef 11.16.4 with Ubuntu 14.04, I get the following error:

```
================================================================================
  Recipe Compile Error in /var/chef/cache/cookbooks/boundary-meter/recipes/default.rb
  ================================================================================

  Net::HTTPServerException
  ------------------------
  404 "Object Not Found"

  Cookbook Trace:
  ---------------
    /var/chef/cache/cookbooks/boundary-meter/libraries/boundary_data.rb:43:in `from_data_bag'
    /var/chef/cache/cookbooks/boundary-meter/libraries/boundary_data.rb:28:in `boundary_data'
    /var/chef/cache/cookbooks/boundary-meter/recipes/dependencies.rb:50:in `block in from_file'
    /var/chef/cache/cookbooks/boundary-meter/recipes/dependencies.rb:49:in `from_file'
    /var/chef/cache/cookbooks/boundary-meter/recipes/default.rb:23:in `from_file'

  Relevant File Content:
  ----------------------
  /var/chef/cache/cookbooks/boundary-meter/libraries/boundary_data.rb:

   36:      end
   37:
   38:      private
   39:
   40:      def from_data_bag(value, namespace)
   41:        databag, item = namespace.split('_')
   42:
   43>>       if data_bag(databag).include?(item)
   44:          return data_bag_item(databag, item)[value]
   45:        end
   46:
   47:        nil
   48:      end
   49:
   50:      def from_node_attr(value, namespace)
   51:        return node[namespace][value]
   52:      end
```

I don't have a data bag it's looking for which is returning a 404. Seems this library needs some more error handling to properly return a nil if possible.

**Comment by sigil66** [comment]
Resolved.
